name: Recent Activity
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  build:
    name: Update Profile README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: 'recent-activity.config.yml'