name: Update README

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with readme-engine
        uses: thisisrick25/readme-engine@v2 # Use the latest major version
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLUGINS: prs, notable-contributions, wakatime
          COMMIT_AUTHOR_NAME: thisisrick25
          COMMIT_AUTHOR_EMAIL: swapnaneel06@gmail.com
          PLUGIN_CONFIG: '{"wakatime":{"sections":["last30Total","allTimeTotal","last30Languages"]}}'